#!/system/bin/sh
# 
# Print startup info 
#
L="log -p i -t bloom"

$L " ____  _                       "
$L "| __ )| | ___   ___  _ __ ___  "
$L "|  _ \\| |/ _ \\ / _ \\| '_ \` _ \\ "
$L "| |_) | | (_) | (_) | | | | | |"
$L "|____/|_|\\___/ \\___/|_| |_| |_|"

$L "Welcome to Android $(getprop ro.build.version.release) / BloomOS-$(getprop ro.bloom.version)"
