BLOOM_VERSION_MAJOR := 1
BLOOM_VERSION_MINOR := 0

BLOOM_VERSION := $(BLOOM_VERSION_MAJOR).$(BLOOM_VERSION_MINOR)

BLOOM_BUILDTYPE := UNOFFICIAL

BLOOM_BUILD_DATE := $(shell date -u +%Y%m%d)

BLOOM_DISPLAY_VERSION := \
    BloomOS-$(BLOOM_VERSION)-$(BLOOM_BUILD_DATE)-$(BLOOM_BUILDTYPE)
